FROM ubuntu:22.04 AS buildstage

# Cache hax, so we get a fresh build every time
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

# Install dependencies
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install wget nano unzip

# Copy stuff
RUN mkdir /aq2server
COPY aq2-tng /aq2-tng
COPY q2admin.lua q2a_cw.lua q2a_cw_docker.lua /aq2server/

# Copy configs to aq2server
RUN cp -r /aq2-tng/action /aq2server/
COPY config/* /aq2server/action/
COPY map_overrides/* /aq2server/action/maps/
# tng file contents should be in the aq2-tng repo
#COPY tng/* /aq2server/action/tng/

# Download and extract latest Q2Pro build
RUN wget -qnv https://github.com/actionquake/q2pro/releases/latest/download/q2pro-lin-gcc.zip
RUN unzip q2pro-lin-gcc.zip
RUN mv q2proded /aq2server/q2proded
RUN chmod +x /aq2server/q2proded

# Download and extract latest TNG build
RUN wget -qnv https://github.com/actionquake/aq2-tng/releases/latest/download/tng-lin-x86_64.zip
RUN unzip -o tng-lin-x86_64.zip
RUN mv gamex86_64.so /aq2server/action/gamex86_64.real.so

# Download and extract latest Q2Admin build
RUN wget -qnv https://github.com/actionquake/q2admin/releases/latest/download/q2admin-lin-x86_64.zip
RUN unzip q2admin-lin-x86_64.zip
RUN mv plugins /aq2server
RUN mv gamex86_64.so /aq2server/action/gamex86_64.so

# Make libraries and scripts executable
RUN chmod +x /aq2server/action/gamex* /aq2server/plugins/mvd_transfer.sh

# Cache hax
##ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --no-install-recommends nano wget curl lua5.1 liblua5.1-0-dev libcurl3-gnutls s3cmd ca-certificates -y && update-ca-certificates

COPY --from=buildstage /aq2server /aq2server
# Copy and set entrypoint
COPY entrypoint.sh /aq2server
ENTRYPOINT /aq2server/entrypoint.sh

# Maps and skins
COPY fullmaplist.ini /aq2server/action/
COPY skinlist.ini /aq2server/action/
RUN mkdir -p /aq2server/action/maps

# Logs and Demos
RUN mkdir /aq2server/action/logs
RUN mkdir /aq2server/action/demos

# Sounds
COPY sndlist.ini tourney.ini /aq2server/action/

# Create user and add rights to aq2server
RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo -u 1001 admin
RUN chown -R admin /aq2server
USER admin
WORKDIR /aq2server

# S3CFG for S3 demo uploads
COPY s3cfg /home/admin/.s3cfg

# motd.txt
ENV MOTD '======= Welcome!  Play nice. ======='

# teamplay.ini
ENV TEAM_1_NAME 'Team 1'
ENV TEAM_1_SKIN 'male/ctf_r'
ENV TEAM_2_NAME 'Team 2'
ENV TEAM_2_SKIN 'male/ctf_b'
ENV TEAM_3_NAME 'Team 3'
ENV TEAM_3_SKIN 'male/ctf_g'

# config.cfg
# Server settings
ENV HOSTNAME AQtion Teamplay
ENV PORT 27910
ENV DEDICATED 1
ENV PUBLIC 1
ENV MAXCLIENTS 18
ENV SV_RESERVED_SLOTS 2
ENV SV_FPS 10
ENV WARMUP 20
ENV WARMUP_BOTS 0
ENV USE_NEWSCORE 3
ENV SKIPMOTD 0
ENV MOTD_TIME 5
ENV CHECK_TIME 5
ENV RADIOLOG 0
ENV USE_VOICE 1
ENV USE_GHOSTS 1
ENV MASTER  "master.quadaver.org master.q2servers.com master.aq2world.com netdome.biz master.quakeservers.net master.quake.services"
ENV _ADMIN AQ2WORLD
ENV AWS_ACCESS_KEY NONE
ENV STAT_APIKEY ""
ENV Q2A_CONFIG q2admin.lua
ENV SCOREBOARD TNMPKDIA
ENV MAP_OVERRIDE "maps/"
ENV SV_CHANGEMAPCMD ""
ENV ROUND_BEGIN 20

# Passwords
ENV RCON_PASSWORD aq2world
ENV SV_PASSWORD ''
ENV SV_MVD_PASSWORD aq2world
ENV SV_RESERVED_PASSWORD ''
ENV NEEDPASS 0

# Map rotation
ENV ACTIONMAPS 1
ENV RROT 0
ENV VROT 0
ENV ROTATION urban2,terminal,tjt,rok,city
ENV EMPTY_ROTATE 0
ENV EMPTY_EXEC ''

# Lag settings
ENV LLSOUND 1
ENV BHOLELIMIT 0
ENV BHOLELIFE 20
ENV SPLATLIMIT 0
ENV SPLATLIFE 25
ENV SHELLOFF 1
ENV SHELLLIMIT 30
ENV SHELLLIFE 1.2
ENV SV_GIB 1
ENV SV_KILLGIB 0
ENV BREAKABLEGLASS 0
ENV GLASSFRAGMENTLIMIT 0
ENV SV_MIN_RATE 5000
ENV SV_MAX_RATE 50000

# Voting
ENV USE_CVOTE 1
ENV CVOTE_MIN 2
ENV CVOTE_NEED 50
ENV CVOTE_PASS 50
ENV CONFIGLISTNAME configlist.ini
ENV USE_MAPVOTE 1
ENV MAPVOTE_MIN 2
ENV MAPVOTE_NEED 66
ENV MAPVOTE_PASS 50
ENV MAPVOTE_WAITTIME 8
ENV MV_PUBLIC 1
ENV USE_KICKVOTE 1
ENV KICKVOTE_MIN 2
ENV KICKVOTE_NEED 32
ENV KICKVOTE_PASS 29
ENV KICKVOTE_TEMPBAN 1
ENV VK_PUBLIC 1
ENV KV_PUBLIC 1
ENV MAPVOTE_NEXT 0
ENV MAPVOTE_NEXT_TIME 0
ENV USE_SCRAMBLEVOTE 1
ENV SCRAMBLEVOTE_PASS 75
ENV SCRAMBLEVOTE_MIN 4
ENV SCRAMBLEVOTE_NEED 0

# Flood and general protections
ENV FLOOD_MSGS 0
ENV FLOOD_PERSECOND 4
ENV FLOOD_WAITDELAY 10
ENV RADIO_REPEAT 3
ENV RADIO_BAN 15
ENV RADIO_TIME 2
ENV RADIO_MAX 4
ENV SV_CRLF 1
ENV SILENCEBAN 1

# Teamkill parameters
ENV MAXTEAMKILLS 3
ENV TKBANROUNDS 0
ENV TWBANROUNDS 0
ENV FF_AFTERROUND 1

# Download settings
ENV ALLOW_DOWNLOAD 1
ENV ALLOW_DOWNLOAD_SKINS 1
ENV ALLOW_DOWNLOAD_PLAYERS 1
ENV ALLOW_DOWNLOAD_PICS 1
ENV ALLOW_DOWNLOAD_SOUNDS 1
ENV SV_REDIRECT_ADDRESS ""
ENV SV_DOWNLOADSERVER http://gameassets.aqtiongame.com/
ENV ALLOW_DOWNLOAD_OTHERS 1
ENV ALLOW_DOWNLOAD_MAPS 1
ENV ALLOW_DOWNLOAD_DEMOS 1

# Video checking
ENV VIDEO_CHECK 1
ENV VIDEO_FORCE_RESTART 0
ENV VIDEO_CHECK_LOCKPVS 1
ENV VIDEO_CHECK_GLCLEAR 1
ENV VIDEO_CHECK_GLDYNAMIC 0
ENV VIDEO_CHECKTIME 35
ENV VIDEO_MAX_3DFX 3.5
ENV VIDEO_MAX_3DFXAM 3.5
ENV VIDEO_MAX_OPENGL 7.0

# General settings
ENV DMFLAGS 768
ENV PUNISHKILLS 1
ENV NOSCORE 0
ENV NOHUD 0
ENV USE_WARNINGS 1
ENV USE_REWARDS 1
ENV USE_BALANCER 1
ENV USE_OLDSPAWNS 0
ENV SV_ALLOW_MAP 0
ENV DEADTALK 0
ENV FORCE_SKIN ""
ENV PPL_IDLETIME 10
ENV SV_IDLEREMOVE 0
ENV SV_IDLEKICK 0
ENV G_SPAWN_ITEMS 0
ENV HEARALL 0
ENV SILENTWALK 0
ENV TRUE_HITBOX 0
ENV USE_KILLCOUNTS 0
ENV PRINTRULES 0
ENV TIMEDMSGS 0

# Misc
ENV USE_BUGGY_BANDOLIER 0
ENV USE_OLDSPAWNS 0
ENV MEDKIT_DROP 0
ENV MEDKIT_TIME 30
ENV MEDKIT_INSTANT 0
ENV RESPAWN_EFFECT 0
ENV ITEM_RESPAWNMODE 0
ENV ITEM_RESPAWN 59
ENV AMMO_RESPAWN 30
ENV WEAPON_RESPAWN 74
ENV WAVE_TIME 5
ENV SPECTATOR_HUD 0
ENV ITEM_KIT_MODE 0
ENV ZOOM_COMP 0

## Game mode settings
ENV DEATHMATCH 1
ENV TEAMPLAY 1
ENV USE_3TEAMS 0
ENV DARKMATCH 0
ENV DAY_CYCLE 30
ENV AUTO_MENU 1
ENV AUTO_JOIN 0
ENV AUTO_EQUIP 0
ENV MM_CAPTAIN_TEAMNAME 0

# Tourney
ENV USE_TOURNEY 0
ENV TOURNEY_LCA 0

# Matchmode
ENV MATCHMODE 0
ENV LIMCHASECAM 0
ENV MM_FORCETEAMTALK 0
ENV MM_ADMINPWD 0
ENV MM_ALLOWLOCK 1
ENV MM_ALLOWCOUNT 3
ENV MM_PAUSETIME 2

# TeamDM
ENV TEAMDM 0
ENV TEAMDM_RESPAWN 2

# CTF
ENV CTF 0
ENV CTF_MODE 2
ENV CTF_FORCEJOIN ""
ENV CTF_DROPFLAG 1
ENV CTF_RESPAWN 4
ENV CTF_MODEL "male"
ENV CAPTURELIMIT 0

# JUMP / JMOD
ENV JUMP 0

# LTK Bots
ENV LTK_LOADBOTS 0
ENV LTK_BOTFILE botdata
ENV LTK_SKILL 5
ENV LTK_CHAT 0
ENV LTK_JUMPY 0
ENV LTK_ROUTING 0
ENV LTK_CLASSIC 1
ENV AM 0
ENV AM_BOTCOUNT 6
ENV AM_TEAM 0
ENV AM_NEWNAMES 1

# Limits
ENV FRAGLIMIT 0
ENV TIMELIMIT 20
ENV ROUNDLIMIT 0
ENV ROUNDTIMELIMIT 3
ENV KNIFELIMIT 40
ENV IPLIMIT 0

# Weapons and items
ENV ALLWEAPON 0
ENV WEAPONS 1
ENV WP_FLAGS 511
ENV ALLITEM 0
ENV ITM_FLAGS 63
ENV IR 1
ENV TGREN 1
ENV DMWEAPON 'MK23 Pistol'
ENV HC_SINGLE 1
ENV USE_CLASSIC 0
ENV DM_CHOOSE 1
ENV DM_SHIELD 30
ENV UVTIME 30
ENV ITEMS 1
ENV ALLOW_HOARDING 0
ENV USE_RANDOMS 0
ENV UNIQUE_WEAPONS 1
ENV UNIQUE_ITEMS 1
ENV GUN_DUALMK23_ENHANCE 1

# Q2proded
ENV LOUD_GUNS 0
ENV SYNC_GUNS 2
ENV SV_UPTIME 1
ENV SV_CALCPINGS_METHOD 2
ENV SV_WATERJUMP_HACK 1
ENV SV_PACKETDUP_HACK 1
ENV NET_MAXMSGLEN 0
ENV LOGFILE_FLUSH 2
ENV LOGFILE 2
ENV LOGFILE_NAME $PORT
ENV LOGFILE_PREFIX "@ [%Y-%m-%d %H:%M] "
ENV STAT_LOGS 0
ENV SERVERID $AWS_ACCESS_KEY

# MVD
ENV SV_MVD_ENABLE 2
ENV SV_MVD_MAXCLIENTS 2
ENV MVD_DEFAULT_MAP wfall
ENV SV_MVD_MAXTIME 30
ENV MVD_SNAPS 2
ENV MVD_WAIT_DELAY 12
ENV SV_MVD_NOMSGS 0
ENV SV_MVD_NOGUN 0

# Antilag
ENV SV_ANTILAG 1
ENV SV_ANTILAG_INTERP 0

# Espionage
ENV ESP 0
ENV ESP_ENHANCEDSLIPPERS 0
ENV ESP_PUNISH 0
ENV ESP_LEADEREQUIP 1
ENV ESP_LEADERENHANCE 1
ENV ESP_MATCHMODE 0
ENV ESP_RESPAWN_UVTIME 10
ENV ESP_ATL 0
ENV ESP_ETV_HALFTIME 1
ENV ESP_DEBUG 0
ENV MEDKIT_MAX 3
ENV MEDKIT_VALUE 25

# Protocol 38
ENV USE_INDICATORS 1
ENV USE_XERP 1
ENV SPECTATOR_HUD 1
ENV NEW_IRVISION 1

# TNG IRC Bot
ENV IRC_SERVER "irc.aq2world.com"
ENV IRC_CHANNEL "#servermsg"
ENV IRC_BOT 0

# Stuffcmd
ENV ADDSTUFFCMD_BEGIN="say vers: \$version"
